spring:
  application:
    name: usercenter

  #mysql数据源配置
  datasource:
    url: jdbc:mysql://106.75.96.225:4040/smartdb_ai_test_1014?characterEncoding=utf-8
    username: smartuser
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
